### ISSUE TITLE
Extra newline in mfdp.dat

### ISSUE THREAD

**Issue by pgysbers** [callum-mccracken/ncsd_python#1]
The "occupation_string" has an extra empty line which ncsd doesn't like.
i.e. in mfdp.dat:

> Major or subshell occupation restrictions for protons, neutrons and (p+n):
>  0 2  0 2  0 4  ! N=0
>  0 6  0 6  0 12  ! N=1
>  0 2  0 6  0 6  ! N=2
>  0 2  0 4  0 4  ! N=3
>  0 2  0 3  0 3  ! N=4
>  0 2  0 2  0 2  ! N=5
>  0 2  0 2  0 2  ! N=6
>  0 2  0 1  0 1  ! N=7
>  0 2  0 1  0 1  ! N=8
>  0 2  0 1  0 1  ! N=9
> 
> Control parameters for multiple-G calculations:

I suspect the culprit is in multi_modules/parameter_calculations.py

```
        if N != m.N_1max:
            line += "\n"
```

where "N" should be "Nshell"?

**Comment by callum-mccracken** [comment]
Closed by pull request
